### ISSUE TITLE
radio checked=checked comparing a string against a datetime?

### ISSUE THREAD

**Issue by neilferreira** [Pylons/pyramid_simpleform#20]
Any idea if I can get this working somehow?  The functionality that checks if the value should be checked is comparing a datetime against a string?

```
    def radio(self, name, value=None, checked=False, label=None, **attrs):
        """
        Outputs radio input.
        """
        checked = self.data.get(name) == value or checked
        return tags.radio(name, value, checked, label, **attrs)
```
```
(Pdb) value
'05/08/15'
(Pdb) self.data.get(name)
datetime.date(2015, 5, 8)
(Pdb) 
```

```
${form.radio('delivery_schedule_date', value=date['date'].strftime('%x')
```

```
    delivery_schedule_date = validators.DateConverter(
        not_empty=True,
        messages={'empty': 'Please select a date'})
```

**Comment by stevepiercy** [comment]
This issue tracker is not an appropriate venue to request support. This is used for reporting bugs or submitting pull requests.

For support of any project under the Pylons Project, please read:
http://www.pylonsproject.org/community/get-support

Either the [pylons-discuss mail list](http://groups.google.com/group/pylons-discuss/) or the #pyramid channel on irc.freenode.net would be appropriate.
