### ISSUE TITLE
Python 3.5 compatability

### ISSUE THREAD

**Issue by J20S** [Pylons/pyramid_simpleform#25]
Hi,

It seems like pyramid_simpleform doesn't work with Python 3.5.

I got syntax error when I call `from pyramid_simpleform import Form`.

Is there any workaround to use FormEncode with Pyramid on Python 3.5?

Or just a general question, is there any recommended form handling library for Pyramid on Python 3.5?

Any help is much appreciated!

**Comment by stevepiercy** [comment]
This seems to be a duplicate of #16.

**Comment by bertjwregeer** [comment]
This is now tested in #26, @lambacck mentioned he would be doing a new release in #16. Closing.
