### ISSUE TITLE
fix the docs to use pylons-sphinx-theme instead of a git submodule

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid_simpleform#27]
See pyramid_jinja2:

https://github.com/Pylons/pyramid_jinja2/blob/master/docs/conf.py
https://github.com/Pylons/pyramid_jinja2/blob/master/rtd.txt
https://github.com/Pylons/pyramid_jinja2/blob/master/setup.py#L50

As well as specific RTD config to use `rtd.txt`.

**Comment by bertjwregeer** [comment]
One a seperate note, I did remove the docs testenv in tox because there wasn't one before. Feel free to crib that from pyramid or webob's tox.ini.

**Comment by stevepiercy** [comment]
I can do this tonight, if someone does not beat me to it.
https://github.com/pylons/pylons-sphinx-themes

**Comment by stevepiercy** [comment]
Docs are currently hosted at:
http://packages.python.org/pyramid_simpleform/

I assume that should that be?
http://docs.pylonsproject.org/projects/pyramid_simpleform/en/latest/

It looks like GitHub is already configured with a webhook to use RTD already.

Also on RTD, @lambacck would you please add me and anyone else from Pylons Project as an Owner on: http://readthedocs.org/projects/pyramid-simpleform/ I am username stevepiercy. Thank you!

**Comment by stevepiercy** [comment]
Reopening because we need to configure RTD to use the file `rtd.txt` under Advanced Settings.

![google chrome001](https://cloud.githubusercontent.com/assets/102112/25509557/bb8b9352-2b6e-11e7-8a9e-78acb7f14fef.png)

**Comment by stevepiercy** [comment]
@lambacck not sure if this got lost in the noise, but this is blocked until either you grant someone else the role of Owner on RTD for this repo so we can configure it as noted above or you can do so yourself. I'd be happy to do so, username stevepiercy.

**Comment by lambacck** [comment]
@stevepiercy I added you and @mmerickel. I added the rtd.txt but the build is still failing looking to TeX files?

**Comment by stevepiercy** [comment]
I temporarily unticked the build of PDF under Advanced Settings to at least have a recent HTML version published, then ticked it back. I tried setting the Python interpreter to use CPython 3, but that failed, too.

There are two error messages:
https://readthedocs.org/projects/pyramid-simpleform/builds/5353532/

```bash
======================================================================
ERROR: test_render_with_htmlfill (pyramid_simpleform.tests.TestFormencodeForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyramid-simpleform/checkouts/latest/pyramid_simpleform/tests.py", line 473, in test_render_with_htmlfill
    config.include('pyramid_mako')
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyramid-simpleform/envs/latest/local/lib/python3.5/site-packages/pyramid/config/__init__.py", line 776, in include
    c = self.maybe_dotted(callable)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyramid-simpleform/envs/latest/local/lib/python3.5/site-packages/pyramid/config/__init__.py", line 876, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyramid-simpleform/envs/latest/local/lib/python3.5/site-packages/pyramid/path.py", line 320, in maybe_resolve
    return self._resolve(dotted, package)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyramid-simpleform/envs/latest/local/lib/python3.5/site-packages/pyramid/path.py", line 327, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyramid-simpleform/envs/latest/local/lib/python3.5/site-packages/pyramid/path.py", line 376, in _zope_dottedname_style
    found = __import__(used)
ImportError: No module named 'pyramid_mako'
```

It looks like the tests need to be updated.

**Comment by bertjwregeer** [comment]
stevepiercy: https://github.com/Pylons/pyramid_simpleform/blob/master/setup.py#L25 add `pyramid_mako` to that list.

**Comment by stevepiercy** [comment]
Thanks @bertjwregeer. That took care of two errors. PDF still does not build.

There's a warning that might offer a clue.

```
WARNING: "latex_documents" config value references unknown document latexindex
```

Perhaps a comparison of `conf.py` between this project and Pyramid's?

Also does RTD pay attention to a project's `Makefile`? I don't think it does, and a search of its docs for "makefile" returns no results.

**Comment by bertjwregeer** [comment]
It does not use the Makefile.

**Comment by stevepiercy** [comment]
Well, I tried, but I give up. I cannot figure out all the bits and pieces to get the PDF to build locally, and it looks like it was originally copied from Pyramid when it was first created. Someone else with sufficient knowledge, caring, or patience will have to figure out how to build PDF.

FWIW, I can build Pyramid's docs as PDF, but I have to suppress dozens of warnings.

**Comment by mmerickel** [comment]
Thanks @stevepiercy - I will see if I can figure out what's going on.

**Comment by bertjwregeer** [comment]
Issue is here:

https://github.com/Pylons/pyramid_simpleform/blob/master/docs/conf.py#L204

`latexindex` here refers to the file to be used as the index file instead of `index.rst`, notice that Pyramid has: https://github.com/Pylons/pyramid/blob/master/docs/latexindex.rst

**Comment by stevepiercy** [comment]
That feeling when you stare at something too long so that you no longer see it. Thanks again @bertjwregeer!

We're good now:
http://readthedocs.org/projects/pyramid-simpleform/downloads/pdf/latest/
