### ISSUE TITLE
Update readme to point to correct URL

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid_simpleform#34]
We typically point `http://docs.pylonsproject.org/projects/<project_name>/en/latest/` to `http://<project_name>.readthedocs.io/en/latest/`, but I don't know who does that or how. Anyone know? Is that @blaflamme ?

For now I've merged a PR that at least points to a current URL, just not canonical.

**Comment by mmerickel** [comment]
I have enabled http://docs.pylonsproject.org/projects/pyramid-simpleform/en/latest/. It is done by adding the project as a subproject to the Pylons project on RTD.

**Comment by stevepiercy** [comment]
Thanks @mmerickel! I've pushed a PR, and will merge when CI passes.
